### ISSUE TITLE
why did the shape is not the same

### ISSUE THREAD

**Issue by LeifSun** [Lotayou/densebody_pytorch#35] opened 2019-06-19 01:32 UTC
After I trained it several epoch ,The problem shows that ：
Traceback (most recent call last):
File "nohup_train.py", line 120, in 
visualizer.save_results(model.get_current_visuals(), epoch, i)
File "/data/home/data_utils/visualizer.py", line 48, in save_results
resampled_verts = self.UV_sampler.resample(self.tensor2numpy(fake_UV))
File "/data/home/data_utils/uv_map_generator.py", line 409, in resample
vt_3d = np.stack(vt_3d)
File "/opt/conda/lib/python3.6/site-packages/numpy/core/shape_base.py", line 416, in stack
raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
can you help me analyze the problem?

**Comment by Lotayou** [comment] 2019-06-20 07:05
I'm afraid there is not enough information to pinpoint the issue... Personally I would suggest you ignore the issue and continue training from your last saved checkpoint, since the error seems to happen at result saving stage, which should not affect the training dynamics. You can try to catch the ValueError exception and print the shape of `vt_3d` to better diagnose the problem.

**Comment by zhou07** [comment] 2019-06-30 14:01
Hi, 
I have the same problem in the train, and now, do you solve the problem?

**Comment by GuodongQi** [comment] 2019-07-02 04:14
same problem,
the loss is larger and larger，and  the uv-map predicted is worse and worse. 
![003_01499](https://user-images.githubusercontent.com/18243549/60482118-e3be5180-9cc2-11e9-8152-14024fedcc6f.png)

**Comment by Lotayou** [comment] 2019-07-02 04:44
Tune down learning rate may help, and remember, NEVER use TV loss as the paper claims, it only makes things worse

**Comment by GuodongQi** [comment] 2019-07-04 02:15
> Tune down learning rate may help, and remember, NEVER use TV loss as the paper claims, it only makes things worse

Hello, I set lr = 1e-5 (previously 1e-4 )，16 batch_sizae,  resenet backbone,  only l1 loss, other params(which locate in train.sh and train.py) are default.  The errors didnot appear during training.
After 70 epoch,  the training loss reduced from 0.28 to 0.244.  Actually， it reduced to 0.24 in 24 epoch,  and varied in 0.22-0.25 in remaining epoch. 

Here is the example in 70 epoch.

![070_01999](https://user-images.githubusercontent.com/18243549/60634883-332b8b80-9e43-11e9-9aaf-160d97651259.png)
and the .obj 
![2019-07-04_095317](https://user-images.githubusercontent.com/18243549/60634974-88679d00-9e43-11e9-858c-38baedcb5b60.png)
rotate it 
![2019-07-04_095037](https://user-images.githubusercontent.com/18243549/60635033-bfd64980-9e43-11e9-8a8b-139f802843f7.png)

human is distort, and the result is not satisfied. 
i think maybe the learning rate is too small, i will try learning rate = 5e-5 later.

what do you think of the cause to  result? thanks

**Comment by Lotayou** [comment] 2019-07-04 02:25
You are right, definitely learning rate too small:) The result you showcased looks like what I got after the first 2~3 epochs, and the result can be dramatically improved after this. Maybe you can try the so-called [Cycle-learning-rate](https://towardsdatascience.com/adaptive-and-cyclical-learning-rates-using-pytorch-2bf904d18dee). I've never tried that in my experiment but it seems a promising solution to your current problem. Best of luck!

**Comment by zhou07** [comment] 2019-07-04 15:31
> > Tune down learning rate may help, and remember, NEVER use TV loss as the paper claims, it only makes things worse
> 
> Hello, I set lr = 1e-5 (previously 1e-4 )，16 batch_sizae, resenet backbone, only l1 loss, other params(which locate in train.sh and train.py) are default. The errors didnot appear during training.
> After 70 epoch, the training loss reduced from 0.28 to 0.244. Actually， it reduced to 0.24 in 24 epoch, and varied in 0.22-0.25 in remaining epoch.
> 
> Here is the example in 70 epoch.
> 
> ![070_01999](https://user-images.githubusercontent.com/18243549/60634883-332b8b80-9e43-11e9-9aaf-160d97651259.png)
> and the .obj
> ![2019-07-04_095317](https://user-images.githubusercontent.com/18243549/60634974-88679d00-9e43-11e9-858c-38baedcb5b60.png)
> rotate it
> ![2019-07-04_095037](https://user-images.githubusercontent.com/18243549/60635033-bfd64980-9e43-11e9-8a8b-139f802843f7.png)
> 
> human is distort, and the result is not satisfied.
> i think maybe the learning rate is too small, i will try learning rate = 5e-5 later.
> 
> what do you think of the cause to result? thanks

Hello,
Do you have this problem that the shape is not the same when you train the model? If you have, can you share the methods to solve the problem?

**Comment by zhou07** [comment] 2019-07-04 15:32
@GuodongQi 
Hello,
Do you have this problem that the shape is not the same when you train the model? If you have, can you share the methods to solve the problem?

**Comment by Lotayou** [comment] 2019-07-05 00:33
@zhou07 @GuodongQi Guys I'm gonna close this issue for now since the subject matter we are discussing is not what the title suggests anymore. But feel free to open a new issue and discuss about the training tricks. Best of luck:)

**Closed as completed by Lotayou** 2019-07-05 00:33 UTC

**Comment by GuodongQi** [comment] 2019-07-05 04:11
> @GuodongQi
> Hello,
> Do you have this problem that the shape is not the same when you train the model? If you have, can you share the methods to solve the problem?

yep, I have the problem which shows shape is not the same when i set lr=1e-4.  I think it is because the training became worse, and maybe predicted some bad value(such as nan, inf etc...), see my first comment. 
When i turn down learn rate, there is no such problem, as my second comment show.  So I think it's not Human36M UV dataset but  training strategy matters.  
At last, I suggest you change lr = 1e-5
